### PR TITLE
[libsailfishapp] Let Qt Creator enable QML debugging by default for QML-only apps. Contribute to JB#7833

### PR DESCRIPTION
**Pull request by martyone**

### CODE REVIEW

**Comment by jpetrell** [comment]
How does "QT += quick qml" relate to "Make QML debugging enabled by default"?

Anything that is eventually meant to be installed on user's devices should not have debug TCP/IP ports open by default due to security considerations.

**Comment by martyone** [comment]
@jpetrell did you read whole commit message? :) I will adjust the title a bit

**Comment by martyone** [comment]
Here is the related Qt Creator source https://github.com/sailfish-sdk/sailfish-qtcreator/blob/master/src/plugins/qmakeprojectmanager/qmakeproject.cpp#L572

**Comment by martyone** [comment]
Added both "quick" and "qml" for consistency with https://github.com/sailfish-sdk/libsailfishapp/blob/master/data/sailfishapp.prf#L36

**Comment by jpetrell** [comment]
LGTM

**Pull request merged**
